---
title: "Map and use case plots for JOHD"
author: "Sandra Auderset"
format: pdf
editor: visual
---

```{r}
#| include: false
library(here)
library(tidyverse)
library(ggpubr)
library(ggsci)
library(janitor)
library(viridis)
```

# Map of languages

Map showing the languages with group affiliation included in the current release.

```{r}
#| include: false
# packages and keys for maps
library(ggmap)
library(ggrepel)
library(ggsci)
library(ggthemes)
library(cowplot)
library(sf)

# Google Maps and Stadia Maps APIs
register_google(key = "AIzaSyBgaOp_Lnz-A2vmQrIBKOxX67uxLgW-Z8M", write = FALSE)
register_stadiamaps("3a811dbc-3a12-4a65-a604-94e474a482af", write = FALSE)
```

```{r}
# read in metadata
metadata <- read_tsv(here("language_metadata.tsv"))
```

```{r}
# create base map by finding edge points
summary(metadata$Longitude)
summary(metadata$Latitude)
# base map
map_northeast <- get_googlemap(center = c(lon = 93, lat = 23.6),
                               zoom = 7,
                               maptype = "hybrid")
# add points
map_ne_sample <- ggmap(map_northeast) +
  geom_point(aes(x = Longitude, y = Latitude, color = Group), data = metadata, size = 3.5) +
  geom_label_repel(aes(x = Longitude, y = Latitude, label = Language_Name, segment.colour = "white"), data = metadata,
                    point.padding = 0.3,
                    box.padding = 0.7,
                    min.segment.length = 0.1,
                   size = 4) + 
  scale_color_tron(name = "Group") +
  ggthemes::theme_map()
map_ne_sample

# write out to file
# ggsave(here("plots/map_languages.png"), map_ne_sample, height = 15, width = 15, units = "cm", dpi = 600)
```

Map of India with square indicating the region of the detailed map.

```{r}
# base map india
map_india <- get_stadiamap(bbox = c(73, 7, 98, 31),
                           maptype = "stamen_toner",
                           zoom = 5)

# add square
map_india_sq <- ggmap(map_india) +
  geom_rect(aes(xmin = 89.5, xmax = 96.5, ymin = 20, ymax = 26.5), 
             fill = NA, color = "red", linewidth = 0.5) +
  ggthemes::theme_map() +
  theme(panel.border = element_rect(colour = "black", fill = NA, size = 1))
map_india_sq
```

Combine the maps into one.

```{r}
map_combined <- ggdraw() +
  draw_plot(map_ne_sample) +
  draw_plot(map_india_sq, 
            x = -0.31, y = 0.64, 
            height = 0.35,
            valign = 0, halign = 0)
map_combined

# write out to file
ggsave(here("plots/map_languages_inset.png"), map_combined, height = 15, width = 15, units = "cm", dpi = 600)
```

# Use case: Distributional profile per language

We create a plot showing a summary of the distribution of each morph in the data set.

```{r}
# language name as string
lang_t <- ("ranglong")
# language name as object
lang_o <- noquote(lang_t)

```

```{r}
# read in scenario file, sort
scenarios <- read_csv(here("scripts/scenarios.csv")) %>%
  mutate(across(ends_with("_Number"), ~factor(.x, levels = c("SG", "DU", "PL")))) %>%
  mutate(across(ends_with("_Clusivity"), ~factor(.x, levels = c("EXCL", "INCL")))) %>%
  arrange(A_Person, A_Number, A_Clusivity, Marking_Type, Scen_Person, O_Number)
glimpse(scenarios)

# read in forms and morphemes, merge each with scenarios
forms_scen <- read_csv(here("PARALEX/ranglong/ranglong_forms.csv")) %>%
  left_join(., scenarios, by = c("cell"="Scenario_ID"))

morphs_scen <- read_csv(here("PARALEX/ranglong/ranglong_morphemes.csv")) %>%
  separate_longer_delim(in_scenarios, delim = ";") %>%
  separate_longer_delim(in_forms, delim = ";") %>%
  distinct() %>%
  mutate(across(starts_with("in_"), ~str_squish(.x))) %>%
  left_join(., scenarios, by = c("in_scenarios"="Scenario_ID")) %>%
  mutate(across(c(A_Number, O_Number), ~factor(.x, levels = c("SG", "DU", "PL"))),
         position = factor(position, levels = c("pre", "post", "free")),
         Scen_Person_Number = factor(Scen_Person_Number, levels = scenario_levels)) %>%
  droplevels() %>% 
  distinct() %>%
  arrange(morpheme, position, Scen_Person_Number)
glimpse(morphs_scen)
```


